spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<db_name>?useSSL=false
    username:
    password:

  redis:
    host:
    port:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: google_app_id
            clientSecret: google_app_secret
            redirectUriTemplate: "{baseUrl}/v1/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: facebook_app_id
            clientSecret: facebook_app_secret
            redirectUriTemplate: "{baseUrl}/v1/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile

        provider:
          facebook:
            authorizationUri: https://www.FACEBOOK.com/v3.0/dialog/oauth
            tokenUri: https://graph.FACEBOOK.com/v3.0/oauth/access_token
            userInfoUri: https://graph.FACEBOOK.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

raas:
  baseUrl:
  XClientId:
  XClientSecret:

mail:
  host:
  port:
  username:
  password:
  from: no-reply@XYPAY.com
  auth: true
  protocol: smtps
  starttls: true
  ssl: true
  verificationapi: http://localhost:3000/user/verify-email?token=
  resetpasswordapi: http://localhost:3000/user/reset-password?token=
  baseUrl: http://localhost:3000/
  moneytunSupport: support@moneytun.com
  moneytunBaseUrl: https://moneytun.com/
  customerSupportEmail: fir@mailinator.com
  customerSupportPhoneNumber: +232-310-91576
  supportAdmins:
  supportAssistants:
  termsAndPrivacyPolicy: https://www.machnetinc.com/licensing/#moneytun

twilio:
  accountSid:
  authToken:
  fromPhoneNumber:

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the sender and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  subscriptionsecret:

server:
  error:
    include-stacktrace: never
  use-forward-headers: true

sentry:
  dsn:
  in-app-includes: com.machpay.affiliate
  logging:
    minimum-breadcrumb-level: debug
    minimum-event-level: warn
  environment:
  server-name:

test:
  user:
    email: <test_user_email>

migration:
  states: # Two char state code separated by comma. Eg: NY, MI, CA

reCAPTCHA:
  URI: https://www.google.com/recaptcha/api/siteverify
  private-key:
  threshold-score: # It can have value from 0.0 to 1.0

features:
  reCAPTCHAEnabled: true
