-- Data population for licencing information

START TRANSACTION;

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'PO Box 110807, Juneau, AK 99811-0807',
       'dbs.licensing@alaska.gov',
       null,
       null,
       null,
       'Alaska Division of Banking and Securities',
       'Division of Banking & Securities',
       'Alaska Division of Banking and Securities',
       'Nine Zero Seven Four Six Five Two Five Two One',
       'https://www.commerce.alaska.gov/web/dbs',
       id,
       null
FROM state WHERE code = "AK";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'Po Box 640, Richmond, Virginia 23218-0640',
       'BFIQuestions@scc.virginia.gov',
       '(804) 371-9416',
       null,
       null,
       'Virginia Bureau of Financial Institutions',
       null,
       'Virginia Bureau of Financial Institutions',
       '1 (804) 371-9657',
       'https://www.scc.virginia.gov/bfi',
       id,
       null
FROM state WHERE code = "VA";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1714 Lincoln Ave., Suite 2, Pierre, SD 57501',
       'banking@state.sd.us',
       null,
       null,
       null,
       'South Dakota Division of Banking',
       null,
       'South Dakota Division of Banking',
       '(605) 773-3421',
       'www.banking.sd.gov',
       id,
       null
FROM state WHERE code = "SD";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '3300 W Sahara Avenue Suite 250, Las Vegas, NV 89102',
       'FIDMaster@fid.state.nv.us',
       null,
       null,
       null,
       'Nevada Department of Business and Industry',
       null,
       'Nevada Department of Business and Industry',
       '(702) 486 – 4120/(866) 858–8951 (toll free)',
       'www.business.nv.gov',
       id,
       null
FROM state WHERE code = "NV";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'PO Box 14480, Salem, OR 97309-0405',
       'DFR.FinancialServicesHelp@dcbs.oregon.gov',
       '503-378-4351',
       null,
       null,
       'Oregon Division of Financial Regulation',
       null,
       'Oregon Division of Financial Regulation',
       '1 888-877-4894',
       'http://dfr.oregon.gov/business/financial-industry/Pages/money-trans.aspx',
       id,
       null
FROM state WHERE code = "OR";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '260 Constitution Plaza, Hartford, CT 06103-1800',
       'dcp.complaints@ct.gov',
       null,
       null,
       null,
       'Connecticut Department of Banking',
       null,
       'Connecticut Department of Banking',
       '860-707-1966',
       'http://www.ct.gov/dob',
       id,
       null
FROM state WHERE code = "CT";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '320 W Washington Suite 550, Springfield, IL 62786',
       null,
       null,
       null,
       null,
       'Illinois Division of Financial Institutions',
       null,
       'Illinois Division of Financial Institutions',
       '1 (888) 473-4858',
       'https://www.idfpr.com/dfi.asp',
       id,
       null
FROM state WHERE code = "IL";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1560 Broadway, Suite 975, Denver, CO 80202',
       'DORA_BankingWebsite@state.co.us',
       null,
       null,
       null,
       'Colorado Division of Banking',
       null,
       'Colorado Division of Banking',
       '303-894-7575',
       'https://www.colorado.gov/pacific/dora/division-banking',
       id,
       null
FROM state WHERE code = "CO";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'Truman State Office Building, Room 630, Jefferson City, MO 65102',
       'finance@dof.mo.gov',
       '(573) 751-9192',
       null,
       null,
       'Missouri Division of Finance',
       null,
       'Missouri Division of Finance',
       '(573) 751-3242',
       'https://finance.mo.gov/',
       id,
       null
FROM state WHERE code = "MO";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'P.O. Box 41200, Olympia, Washington 98504-1200',
       'CSEnforceComplaints@dfi.wa.gov',
       null,
       null,
       null,
       'Washington Department of Financial Institutions',
       'DIVISION OF CONSUMER SERVICES',
       'Washington Department of Financial Institutions',
       '(360) 902-8700 / TDD (360) 664-8126',
       'https://dfi.wa.gov/consumers/money-services-complaint',
       id,
       null
FROM state WHERE code = "WA";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'P.O. Box 146800, Salt Lake City, Utah 84114-6800',
       'complaints.dfi@utah.gov',
       '(801) 538-8894',
       null,
       null,
       'Utah Department of Financial Institutions',
       null,
       'Utah Department of Financial Institutions',
       '1 801-538-8834',
       'https://www.dfi.utah.gov',
       id,
       null
FROM state WHERE code = "UT";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1050 First Street, NE, 801, Washington, DC 20002',
       'oag@dc.gov',
       null,
       null,
       null,
       'District of Columbia Department of Insurance, Securities and Banking',
       null,
       'District of Columbia Department of Insurance, Securities and Banking',
       '(202) 727-8000',
       'https://www.disb.dc.gov',
       id,
       null
FROM state WHERE code = "DC";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'TN Attorney General’s Office, P.O. Box 20207, Nashville, TN 37202',
       'consumer.affairs@ag.tn.gov',
       null,
       null,
       null,
       'Tennessee Department of Financial Institutions',
       'Division of Consumer Affairs',
       'Tennessee Department of Financial Institutions',
       '(615) 741-2236',
       'https://www.tn.gov/tdfi.html',
       id,
       null
FROM state WHERE code = "TN";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'Heritage West Building, Suite 300, 201 East Markham Street, Little Rock, Arkansas 72201-1692',
       'ASDInfo@Arkansas.gov',
       null,
       null,
       null,
       'Arkansas Securities Department',
       null,
       'Arkansas Securities Department',
       '(501)324-9260',
       'https://www.securities.arkansas.gov',
       id,
       null
FROM state WHERE code = "AR";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'P.O. Box 83720, Boise, ID 83720-0031',
       'securities@finance.idaho.gov',
       null,
       null,
       null,
       'Idaho Department of Finance',
       null,
       'Idaho Department of Finance',
       '208-332-8004/1-888-346-3378',
       'https://www.finance.idaho.gov',
       id,
       null
FROM state WHERE code = "ID";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '2601 N. Lamar Blvd, Austin, Texas 78705-429',
       'msb@dob.texas.gov',
       '(512) 475-1288',
       null,
       null,
       'Texas Department of Banking',
       null,
       'Texas Department of Banking',
       '1(877)-276-5554',
       'https://www.dob.texas.gov',
       id,
       null
FROM state WHERE code = "TX";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '200 E. Gaines Street, Tallahassee, FL 32399-0381',
       null,
       null,
       null,
       null,
       'Florida Office of Financial Regulation',
       null,
       'Florida Office of Financial Regulation',
       '1-866-966-7226',
       'http://www.flofr.com',
       id,
       null
FROM state WHERE code = "FL";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'P.O. Box 45025, Newark, NJ 07101',
       'AskConsumerAffairs@dca.lps.state.nj.us',
       null,
       null,
       null,
       'New Jersey Department of Banking and Insurance',
       'Division of Consumer Affairs',
       'New Jersey Department of Banking and Insurance',
       '(973) 504-6200/(800)-242-5846',
       'http://www.state.nj.us/dobi',
       id,
       null
FROM state WHERE code = "NJ";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '2550 Cerrillos Road | P.O. Box 25101 Santa Fe, NM 87504',
       null,
       null,
       null,
       null,
       'New Mexico Financial Institution Division',
       null,
       'New Mexico Financial Institution Division',
       '(505) 476-4885',
       'www.rld.state.nm.us/financialinstitutions',
       id,
       null
FROM state WHERE code = "NM";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'Main Office, Golden Rule Building 85, 7th Place East Suite 280, Saint Paul, Minnesota 55101',
       'consumer.protection@state.mn.us',
       null,
       null,
       null,
       'Minnesota Department of Commerce',
       null,
       'Minnesota Department of Commerce',
       '651-539-1500 (local) /651-539-1600 (complaints)',
       'https://mn.gov/commerce',
       id,
       null
FROM state WHERE code = "MN";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '301 South Park, Suite 316, Helena, MT 59601 PO Box 200546',
       'OCP@mt.gov',
       null,
       null,
       null,
       'Montana Division of Banking and Financial Institutions',
       null,
       'Montana Division of Banking and Financial Institutions',
       '406-444-4500/800-481-6896',
       null,
       id,
       null
FROM state WHERE code = "MT";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '445 Dexter Avenue, Suite 12000, Montgomery, Alabama 36104',
       'asc@asc.alabama.gov',
       null,
       null,
       null,
       'Alabama Securities Commission',
       null,
       'Alabama Securities Commission',
       '334-242-2984/1-800-222-1253',
       'http://asc.alabama.gov',
       id,
       null
FROM state WHERE code = "AL";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1000 Washington Street, 10th floor, Boston, MA 02118-2218',
       'dobconsumer.assistance@mass.gov',
       null,
       null,
       null,
       'Massachusetts Office of Consumer Affairs and Business Regulation',
       null,
       'Massachusetts Office of Consumer Affairs and Business Regulation',
       '1-617-956-1500',
       'https://www.mass.gov/orgs/office-of-consumer-affairs-and-business-regulation',
       id,
       null
FROM state WHERE code = "MA";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '2990 Brandywine Road, Suite 200, Atlanta, Georgia 30341-5565',
       null,
       null,
       null,
       null,
       'Georgia Department of Banking and Finance',
       null,
       'Georgia Department of Banking and Finance',
       '(404) 651-8600 / (800) 869-1123',
       'http://www.dbf.georgia.gov',
       id,
       null
FROM state WHERE code = "GA";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1110 Forrest Avenue, Dover, DE 19904',
       'Investigations.dpr@delaware.gov',
       null,
       null,
       null,
       'Delaware Office of the State Bank Commissioner',
       null,
       'Delaware Office of the State Bank Commissioner',
       '(302) 744-4500',
       'https://www.banking.delaware.gov',
       id,
       null
FROM state WHERE code = "DE";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '4309 Mail Service Center, Raleigh, NC 27699-4309',
       null,
       null,
       null,
       null,
       'North Carolina Commissioner of Banks',
       null,
       'North Carolina Commissioner of Banks',
       '919-733-3016',
       'http://www.nccob.gov',
       id,
       null
FROM state WHERE code = "NC";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '2101 Arena Boulevard, Sacramento, CA 95834',
       'consumer.services@dfpi.ca.gov',
       null,
       null,
       null,
       'California Department of Financial Protection and Innovation (DFPI)',
       null,
       'California Department of Financial Protection and Innovation (DFPI)',
       '1-866-275-2677',
       'http://www.dbo.ca.gov',
       id,
       null
FROM state WHERE code = "CA";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '2000 Schafer Street, Suite G, Bismarck, ND 58501-1204',
       'DFI@ND.gov',
       null,
       null,
       null,
       'North Dakota Department of Financial Institutions',
       null,
       'North Dakota Department of Financial Institutions',
       '701.328.2480',
       'https://www.nd.gov/dfi',
       id,
       null
FROM state WHERE code = "ND";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1 State Street, New York, NY 1000',
       'consumers@dfs.ny.gov',
       '212-480-6282',
       null,
       null,
       'New York Department of Financial Services',
       null,
       'New York Department of Financial Services',
       '800-342-3736',
       'http://www.dfs.ny.gov',
       id,
       null
FROM state WHERE code = "NY";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT 'PO Box 30220, Lansing, MI 48909-7720',
       null,
       '517-335-4978',
       null,
       null,
       'Department of Insurance and Financial Services',
       null,
       'Department of Insurance and Financial Services',
       '877-999-6442',
       'https://www.michigan.gov/difs/',
       id,
       null
FROM state WHERE code = "MI";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '17 N. 2nd Street, Harrisburg, PA 17101',
       null,
       null,
       null,
       null,
       'Pennsylvania Department of Banking and Securities',
       null,
       'Pennsylvania Department of Banking and Securities',
       '1.800.PA.BANKS or 1.800.600.0007',
       'https://www.dobs.pa.gov',
       id,
       null
FROM state WHERE code = "PA";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1100 North Eutaw Street, Suite 611, Baltimore, Maryland 21201',
       'DLFRComplaints-LABOR@maryland.gov',
       null,
       null,
       null,
       'Maryland Office of the Commissioner of Financial Regulation',
       null,
       'Maryland Office of the Commissioner of Financial Regulation',
       '410-230-6100 or 888-784-0136',
       'https://www.dllr.state.md.us/finance',
       id,
       null
FROM state WHERE code = "MD";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '1511 Pontiac Avenue, Cranston, RI 02920',
       'DBR.BankInquiry@dbr.ri.gov',
       null,
       null,
       null,
       'Rhode Island Department of Business Regulation',
       null,
       'Rhode Island Department of Business Regulation',
       '(401) 462-9503',
       'https://dbr.ri.gov/divisions/banking/',
       id,
       null
FROM state WHERE code = "RI";

INSERT INTO license (address,
                     email,
                     fax,
                     license_no,
                     license_type,
                     regulatory_body,
                     regulatory_division,
                     regulatory_name,
                     telephone,
                     website,
                     state_id,
                     state_disclaimer)
SELECT '53 Regional Drive, Suite 200 Concord NH 03301',
       'legal@banking.nh.gov',
       null,
       null,
       null,
       'New Hampshire Banking Department',
       null,
       'New Hampshire Banking Department',
       '(603) 271-3561/ (800) 437-5991',
       'https://www.nh.gov/banking/',
       id,
       null
FROM state WHERE code = "NH";

COMMIT;